function hourlyBid = importBidISONE(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HOURLYBID = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  HOURLYBID = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  hourlyBid = importfile("D:\courses\ECE 4800\Project\power_gen_cost\data\2019_DAM_BID_ISONE\hbdayaheadenergyoffer_20190101.csv", [7, 7998]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Nov-2020 14:27:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [7, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 36);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Date", "Hour", "ParticipantID", "AssetID", "MustTakeEnergy", "MaximumDailyEnergyAvailable", "EconomicMaximum", "EconomicMinimum", "ColdStartupPrice", "IntermediateStartupPrice", "HotStartupPrice", "NoLoadPrice", "Segment1Price", "Segment1MW", "Segment2Price", "Segment2MW", "Segment3Price", "Segment3MW", "Segment4Price", "Segment4MW", "Segment5Price", "Segment5MW", "Segment6Price", "Segment6MW", "Segment7Price", "Segment7MW", "Segment8Price", "Segment8MW", "Segment9Price", "Segment9MW", "Segment10Price", "Segment10MW", "Claim10", "Claim30", "UnitStatus"];
opts.SelectedVariableNames = ["Date", "Hour", "ParticipantID", "AssetID", "MustTakeEnergy", "MaximumDailyEnergyAvailable", "EconomicMaximum", "EconomicMinimum", "ColdStartupPrice", "IntermediateStartupPrice", "HotStartupPrice", "NoLoadPrice", "Segment1Price", "Segment1MW", "Segment2Price", "Segment2MW", "Segment3Price", "Segment3MW", "Segment4Price", "Segment4MW", "Segment5Price", "Segment5MW", "Segment6Price", "Segment6MW", "Segment7Price", "Segment7MW", "Segment8Price", "Segment8MW", "Segment9Price", "Segment9MW", "Segment10Price", "Segment10MW", "Claim10", "Claim30", "UnitStatus"];
opts.VariableTypes = ["string", "datetime", "double", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "ParticipantID", "AssetID", "UnitStatus"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "MM/dd/yyyy");
opts = setvaropts(opts, ["Segment8Price", "Segment8MW", "Segment9Price", "Segment9MW", "Segment10Price", "Segment10MW"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Segment8Price", "Segment8MW", "Segment9Price", "Segment9MW", "Segment10Price", "Segment10MW"], "ThousandsSeparator", ",");

% Import the data
hourlyBid = readtable(filename, opts);
hourlyBid = hourlyBid(~ismissing(hourlyBid.ParticipantID), :);
hourlyBid.DateTime = datetime(year(hourlyBid.Date),month(hourlyBid.Date),day(hourlyBid.Date),hourlyBid.Hour,0,0);
hourlyBid.DateTime.Format = 'MM/dd/yyyy hh:mm:ss';
end