function generation = importGenerationData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EMISSION201901 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  EMISSION201901 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  emission201901 = importfile("D:\EERL\EPA_AMPD\emission_201901.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Sep-2020 20:58:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 26);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "FacilityName", "FacilityID", "UnitID", "Var5", "Var6", "Date", "Hour", "OperatingTime", "GrossLoadMW", "Var11", "Var12", "Var13", "Var14", "Var15", "HeatInputMMBtu", "County", "Var18", "Var19", "Var20", "Var21", "UnitType", "FuelTypePrimary", "Var24", "FacilityLatitude", "FacilityLongitude"];
opts.SelectedVariableNames = ["FacilityName", "FacilityID", "UnitID", "Date", "Hour", "OperatingTime", "GrossLoadMW", "County", "UnitType", "HeatInputMMBtu", "FuelTypePrimary", "FacilityLatitude", "FacilityLongitude"];
opts.VariableTypes = ["string", "categorical", "categorical", "categorical", "string", "string", "datetime", "double", "double", "double", "string", "string", "string", "string", "string", "double", "categorical", "string", "string", "string", "string", "categorical", "categorical", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var5", "Var6", "Var11", "Var12", "Var13", "Var14", "Var15", "Var18", "Var19", "Var20", "Var21", "Var24"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "FacilityName", "FacilityID", "UnitID", "Var5", "Var6", "Var11", "Var12", "Var13", "Var14", "Var15", "County", "Var18", "Var19", "Var20", "Var21", "UnitType", "FuelTypePrimary", "Var24"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "MM/dd/yyyy");

% Import the data
generation = readtable(filename, opts);

% Replacing GrossLoad NaN with 0
generation.GrossLoadMW(ismissing(generation.GrossLoadMW)) = 0;
generation.HeatInputMMBtu(ismissing(generation.HeatInputMMBtu)) = 0;
end